utils/models.py
from datetime import datetime

from sqlalchemy import Column, Integer, String, Boolean, DateTime

from .database import Base


class User(Base):
    __tablename__ = "users"

    address = Column(String(42), primary_key=True, nullable=False)
    username = Column(String(10), unique=True, nullable=True)
    nonce = Column(String(11), nullable=False)
    active = Column(Boolean, default=False, nullable=False)

    @property
    def is_authenticated(self):
        return True

    @property
    def is_active(self):
        return self.active

    @property
    def is_anonymous(self):
        return False

    def get_id(self):
        return self.address

    def __repr__(self):
        return f"<User {self.address}>"


class Post(Base):
    __tablename__ = "posts"

    author = Column(String(10), primary_key=True, nullable=False)
    id = Column(String(8), primary_key=True, nullable=False)
    title = Column(String(100), nullable=False)
    content = Column(String(2000), nullable=False)
    created_at = Column(DateTime, default=datetime.now(), nullable=False)

    def __repr__(self):
        return f"<Post {self.author} {self.id}>"


class Tip(Base):
    __tablename__ = "tips"

    id = Column(Integer, primary_key=True, autoincrement=True, nullable=False)
    sender = Column(String(10), nullable=False)
    recipient = Column(String(10), nullable=False)
    amount = Column(String(10), nullable=False)
    post_id = Column(String(8), nullable=False)
    tx_hash = Column(String(66), nullable=True)
    notified = Column(Boolean, default=False, nullable=False)

    def __repr__(self):
        return f"<Tip {self.sender} {self.recipient}>"

utils/forms.py
from flask_wtf import FlaskForm

from wtforms import StringField, TextAreaField, FloatField
from wtforms.validators import InputRequired, Length


class UsernameForm(FlaskForm):
    username = StringField(
        "Username",
        validators=[InputRequired(), Length(min=5, max=10)],
    )


class PostForm(FlaskForm):
    title = StringField(
        "Title",
        validators=[InputRequired(), Length(min=10, max=100)],
    )
    content = TextAreaField(
        "Content",
        validators=[InputRequired(), Length(min=5, max=1000)],
    )


class TipForm(FlaskForm):
    sender = StringField(
        "Sender",
    )

    recipient = StringField(
        "Recipient",
    )

    amount = FloatField(
        "Amount",
        validators=[InputRequired()],
    )

blueprints/__init__.py
from .app import app_bp
from .auth import auth_bp
from .meta import meta_bp
from .posts import posts_bp
from .tips import tips_bp

blueprints/app/__init__.py
from flask import Blueprint

app_bp = Blueprint("app", __name__)

from . import routes

blueprints/app/routes.py
from . import app_bp

from flask import render_template
from flask_login import login_required


@app_bp.route("/app", methods=["GET"])
@login_required
def _index():
    return render_template("app/index.html")

blueprints/meta/__init__.py
from flask import Blueprint

meta_bp = Blueprint("meta", __name__)

from . import routes

blueprints/meta/routes.py
from . import meta_bp

from flask import render_template

from utils.crud import get_latest_posts


@meta_bp.route("/", methods=["GET"])
def _index():
    posts = get_latest_posts()

    return render_template("meta/index.html", posts=posts)

blueprints/posts/__init__.py
from flask import Blueprint

posts_bp = Blueprint("posts", __name__)

from . import routes

blueprints/posts/routes.py
from . import posts_bp

from flask import render_template, redirect, url_for, flash
from flask_login import current_user, login_required

import secrets

from utils.forms import PostForm
from utils.crud import get_post, get_user_posts, new_post, update_post, delete_post


@posts_bp.route("/posts/me", methods=["GET"])
@login_required
def _me():
    posts = get_user_posts(current_user.username)

    return render_template("posts/me.html", posts=posts)


@posts_bp.route("/posts/view/<author>/<post_id>", methods=["GET"])
def _view(author: str, post_id: str):
    post = get_post(author, post_id)

    if not post:
        flash("Post not found.", "error")
        return redirect(url_for("meta._index"))

    return render_template("posts/view.html", post=post)


@posts_bp.route("/posts/new", methods=["GET", "POST"])
@login_required
def _new():
    post_form = PostForm()

    if post_form.validate_on_submit():
        post_id = secrets.token_hex(4)
        new_post(
            current_user.username,
            post_id,
            post_form.title.data,
            post_form.content.data,
        )

        flash("Post created.", "success")
        return redirect(url_for("posts._me"))

    return render_template("posts/new.html", post_form=post_form)


@posts_bp.route("/posts/update/<author>/<post_id>", methods=["GET", "POST"])
@login_required
def _update(author: str, post_id: str):
    post = get_post(author, post_id)

    if not post:
        flash("Post not found.", "error")
        return redirect(url_for("posts._me"))

    post_form = PostForm()

    if post_form.validate_on_submit():
        update_post(author, post_id, post_form.title.data, post_form.content.data)

        flash("Post updated.", "success")
        return redirect(url_for("posts._view", author=author, post_id=post_id))

    post_form.title.data = post.title
    post_form.content.data = post.content

    return render_template("posts/update.html", post_id=post.id, post_form=post_form)


@posts_bp.route("/posts/delete/<author>/<post_id>", methods=["GET"])
@login_required
def _delete(author: str, post_id: str):
    post = get_post(author, post_id)

    if not post:
        flash("Post not found.", "error")
        return redirect(url_for("posts._me"))

    delete_post(author, post_id)

    flash("Post deleted.", "success")
    return redirect(url_for("posts._me"))

blueprints/tips/__init__.py
from flask import Blueprint

tips_bp = Blueprint("tips", __name__)

from . import routes

blueprints/tips/routes.py
from . import tips_bp

from flask import request, jsonify, render_template, redirect, url_for, flash
from flask_login import current_user, login_required

from utils.forms import TipForm
from utils.crud import (
    get_post,
    get_user_by_address,
    get_user_by_username,
    record_tip,
    get_sent_tips,
    get_received_tips,
)


@tips_bp.route("/tips/send/<author>/<post_id>", methods=["GET"])
@login_required
def _send(author: str, post_id: str):
    post = get_post(author, post_id)

    if not post:
        flash("Post not found.", "danger")
        return redirect(url_for("meta._index"))

    if author == current_user.username:
        flash("You can't tip your own post.", "danger")
        return redirect(url_for("posts._view", author=author, post_id=post_id))

    user = get_user_by_username(author)

    tip_form = TipForm()
    tip_form.sender.data = current_user.address
    tip_form.sender.render_kw = {"readonly": True}
    tip_form.recipient.data = user.address
    tip_form.recipient.render_kw = {"readonly": True}

    return render_template("tips/send.html", post=post, tip_form=tip_form)


@tips_bp.route("/tips/record", methods=["POST"])
@login_required
def _record():
    data = request.get_json()
    sender = data.get("sender")
    recipient = data.get("recipient")
    amount = data.get("amount")
    post_id = data.get("post_id")
    tx_hash = data.get("txHash")

    username = get_user_by_address(sender).username
    recipient = get_user_by_address(recipient).username

    record_tip(username, recipient, amount, post_id, tx_hash)

    return jsonify({"success": "Tip recorded."}), 200


@tips_bp.route("/tips/view", methods=["GET"])
@login_required
def _view():
    sent_tips = get_sent_tips(current_user.username)
    received_tips = get_received_tips(current_user.username)

    return render_template(
        "tips/view.html", sent_tips=sent_tips, received_tips=received_tips
    )

templates/app/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>App | BlogChain</title>
    {% include "header.html" %}
</head>

<body class="light-theme">
    <div class="container mt-5">
        {% include "navbar.html" %}

        <div class="container mb-5">
            <div class="row justify-content-center">
                <div class="col-md-6 content-box text-center">
                    <h3 class="card-title">Hello, <code>{{ current_user.username }}</code>!</h3>
                    <h4 class="card-title">Your ETH Address: <code>{{ current_user.address }}</code></h4>
                    <br>
                    <a href="{{ url_for('posts._me') }}" class="btn btn-primary">My Posts</a>
                    <a href="{{ url_for('posts._new') }}" class="btn btn-success">Create Post</a>
                    <a href="{{ url_for('auth._settings') }}" class="btn btn-secondary">Settings</a>
                </div>
            </div>
        </div>
    </div>

    {% include "footer.html" %}

    {% include "scripts.html" %}

</body>

</html>

templates/footer.html
<footer class="footer mt-auto py-3">
    <div class="container text-center">
        <span class="text-muted">&copy; <script>document.write(new Date().getFullYear())</script> Sayan "Sn1F3rt" Bhattacharyya • GNU General Public License v3.0</span>
    </div>
</footer>

templates/header.html
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="icon" type="image/png" href="/assets/images/icon.png">
<link rel="stylesheet" href="/assets/css/bootstrap.min.css">
<link rel="stylesheet" href="/assets/css/fontawesome.all.css">
<link rel="stylesheet" href="/assets/css/noty.min.css">
<link rel="stylesheet" href="/assets/css/main.css">
<link id="theme-link" rel="stylesheet" href="/assets/css/light.css">

templates/meta/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>BlogChain</title>
    {% include "header.html" %}
</head>

<body class="light-theme">
    <div class="container mt-5">
        {% include "navbar.html" %}

        <div class="row mt-5 mb-5">
            {% if posts|length == 0 %}
                    <div class="col-md-6 mx-auto">
                        <div class="alert alert-info text-center" role="alert">
                            No posts found.
                        </div>
                    </div>
            {% endif %}

            {% for post in posts %}
                <div class="col-md-6">
                    <div class="post-container">
                        {% if post.author == current_user.username %}
                            <a href="{{ url_for('posts._view', author=post.author, post_id=post.id) }}" title="View Post" class="btn btn-primary post-button-3"><i class="fa-solid fa-eye"></i></a>
                            <a href="{{ url_for('posts._update', author=post.author, post_id=post.id) }}" title="Update Post" class="btn btn-secondary post-button-2"><i class="fa-solid fa-edit"></i></a>
                            <a href="{{ url_for('posts._delete', author=post.author, post_id=post.id) }}" title="Delete Post" class="btn btn-danger post-button-1"><i class="fa-solid fa-trash"></i></a>
                        {% else %}
                            <a href="{{ url_for('posts._view', author=post.author, post_id=post.id) }}" title="View Post" class="btn btn-primary post-button-2"><i class="fa-solid fa-eye"></i></a>
                            <a href="{{ url_for('tips._send', author=post.author, post_id=post.id) }}" title="Tip" class="btn btn-success post-button-1"><i class="fa-solid fa-sack-dollar"></i></a>
                        {% endif %}
                        <h2>{{ post.title }}</h2>
                        {{ post.content|truncate  }}
                        <br><br>
                        <p>
                            <strong>Author:</strong> {{ post.author }}
                            <br>
                            <strong>Date Posted:</strong> {{ post.created_at|format }}
                        </p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    {% include "footer.html" %}

    {% include "scripts.html" %}

</body>

</html>

templates/navbar.html
<div class="row">
    <div class="col-md-6">
        <a href="{{ url_for('meta._index') }}" class="header-link"><h1 class="mb-4">BlogChain</h1></a>
    </div>
    <div class="col-md-6 text-right">
        {% include "theme-toggle.html" %}
        {% if current_user.is_authenticated %}
            <a href="{{ url_for('meta._index') }}" title="Home" class="btn btn-primary"><i class="fa-solid fa-house"></i></a>
            <a href="{{ url_for('app._index') }}" title="Dashboard" class="btn btn-warning"><i class="fa-solid fa-user"></i></a>
            <a href="{{ url_for('posts._me') }}" title="My Posts" class="btn btn-warning"><i class="fa-solid fa-bars"></i></a>
            <a href="{{ url_for('posts._new') }}" title="New Post" class="btn btn-success"><i class="fa-solid fa-plus"></i></a>
            <a href="{{ url_for('tips._view') }}" title="Tips" class="btn btn-info"><i class="fa-solid fa-money-bill-transfer"></i></a>
            <a href="{{ url_for('auth._settings') }}" title="Settings" class="btn btn-secondary"><i class="fa-solid fa-gear"></i></a>
            <button onclick="logout()" class="btn btn-danger">Logout</button>
        {% else %}
            <button onclick="login()" class="btn btn-primary">Login with MetaMask</button>
        {% endif %}
    </div>
</div>

templates/posts/me.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Your Posts | BlogChain</title>
    {% include "header.html" %}
</head>

<body class="light-theme">
    <div class="container mt-5">
        {% include "navbar.html" %}

        <h1 class="mt-3 mb-5 text-center">Your Posts</h1>

        <div class="row mb-5">
            {% if posts|length == 0 %}
                <div class="col-md-6 mx-auto">
                    <div class="alert alert-info text-center" role="alert">
                        No posts found.
                    </div>
                </div>
            {% endif %}

            {% for post in posts %}
                <div class="col-md-6">
                    <div class="post-container">
                        <a href="{{ url_for('posts._view', author=post.author, post_id=post.id) }}" title="View Post" class="btn btn-primary post-button-3"><i class="fa-solid fa-eye"></i></a>
                        <a href="{{ url_for('posts._update', author=current_user.username, post_id=post.id) }}" title="Update Post" class="btn btn-secondary post-button-2"><i class="fa-solid fa-pen-to-square"></i></a>
                        <a href="{{ url_for('posts._delete', author=current_user.username, post_id=post.id) }}" title="Delete Post" class="btn btn-danger post-button-1"><i class="fa-solid fa-trash"></i></a>
                        <h2>{{ post.title }}</h2>
                        <p>{{ post.content|truncate }}</p>
                        <p><strong>Date:</strong> {{ post.created_at|format }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    {% include "footer.html" %}

    {% include "scripts.html" %}

</body>

</html>

templates/posts/new.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>New Post | BlogChain</title>
    {% include "header.html" %}
</head>

<body class="light-theme">
    <div class="container mt-5">
        {% include "navbar.html" %}

        <div class="container mb-5">
            <div class="row justify-content-center">
                <div class="col-md-6 content-box">
                    <h4 class="card-title text-center">Create Post</h4>
                    <form method="POST" action="{{ url_for('posts._new') }}" >
                        {{ post_form.hidden_tag() }}
                        <div class="form-group">
                            {{ post_form.title.label(class="form-control-label") }}
                            {{ post_form.title(class="form-control", placeholder="Enter post title") }}
                        </div>
                        <div class="form-group">
                            {{ post_form.content.label(class="form-control-label") }}
                            {{ post_form.content(class="form-control", placeholder="Enter post content (Markdown supported)") }}
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% include "footer.html" %}

    {% include "scripts.html" %}

</body>

</html>

templates/posts/update.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Update Post | BlogChain</title>
    {% include "header.html" %}
</head>

<body class="light-theme">
    <div class="container mt-5">
        {% include "navbar.html" %}

        <div class="container mb-5">
            <div class="row justify-content-center">
                <div class="col-md-6 content-box">
                    <h4 class="card-title text-center">Edit {{ post_id }}</h4>
                    <form method="POST" action="{{ url_for('posts._update', author=current_user.username, post_id=post_id) }}" >
                        {{ post_form.hidden_tag() }}
                        <div class="form-group">
                            {{ post_form.title.label(class="form-control-label") }}
                            {{ post_form.title(class="form-control", placeholder="Enter post title") }}
                        </div>
                        <div class="form-group">
                            {{ post_form.content.label(class="form-control-label") }}
                            {{ post_form.content(class="form-control", placeholder="Enter post content (Markdown supported)") }}
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% include "footer.html" %}

    {% include "scripts.html" %}

</body>

</html>

templates/posts/view.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>View Post | BlogChain</title>
    {% include "header.html" %}
</head>

<body class="light-theme">
    <div class="container mt-5">
        {% include "navbar.html" %}

        <div class="container mt-5 mb-5">
            <div class="row justify-content-center">
                <div class="col-md-8 content-box low">
                    {% if post.author == current_user.username %}
                        <a href="{{ url_for('posts._update', author=post.author, post_id=post.id) }}" title="Update Post" class="btn btn-primary post-button-2"><i class="fa-solid fa-pen-to-square"></i></a>
                        <a href="{{ url_for('posts._delete', author=post.author, post_id=post.id) }}" title="Delete Post" class="btn btn-danger post-button-1"><i class="fa-solid fa-trash"></i></a>
                    {% else %}
                        <a href="{{ url_for('tips._send', author=post.author, post_id=post.id) }}" title="Tip" class="btn btn-success post-button-1"><i class="fa-solid fa-sack-dollar"></i></a>
                    {% endif %}
                    <h1>{{ post.title }}</h1>
                    <p><strong>Author:</strong> {{ post.author }}</p>
                    <p><strong>Date Posted:</strong> {{ post.created_at|format }}</p>
                    {{ post.content|markdown|safe }}
                </div>
            </div>
        </div>
    </div>

    {% include "footer.html" %}

    {% include "scripts.html" %}

</body>

</html>

templates/scripts.html
<script src="/assets/js/fontawesome.all.js"></script>
<script src="/assets/js/jquery.slim.min.js"></script>
<script src="/assets/js/noty.min.js"></script>
<script src="/assets/js/popper.min.js"></script>
<script src="/assets/js/bootstrap.min.js"></script>

<script>
    const themeToggle = document.getElementById("theme-switch");
    const themeLink = document.getElementById("theme-link");

    if (localStorage.getItem("theme") === "dark") {
        enableDarkTheme();
    }

    themeToggle.addEventListener("change", () => {
        if (themeToggle.checked) {
            enableDarkTheme();
        } else {
            enableLightTheme();
        }
    });

    function enableDarkTheme() {
        themeToggle.checked = true;
        themeLink.href = '/assets/css/dark.css';
        document.body.classList.remove('light-theme');
        document.body.classList.add('dark-theme');
        localStorage.setItem('theme', 'dark');
    }

    function enableLightTheme() {
        themeLink.href = '/assets/css/light.css';
        document.body.classList.remove('dark-theme');
        document.body.classList.add('light-theme');
        localStorage.setItem('theme', 'light');
    }
</script>

<script>
    const provider = window.ethereum;
    const BACKEND_ADDR_AUTH = "http://localhost:5000/auth";

    let accounts = null;
    let message = null;
    let signature = null;

    async function connectWallet() {
        accounts = await provider
            .request({ method: "eth_requestAccounts" })
            .catch((err) => {
        if (err.code === 4001) {
            new Noty({
                type: "error",
                theme: "bootstrap-v4",
                layout: "topCenter",
                text: "Please connect to MetaMask.",
                timeout: 3000
            }).show();
        } else {
            new Noty({
                type: "error",
                theme: "bootstrap-v4",
                layout: "topCenter",
                text: "An error occurred while connecting to MetaMask.",
                timeout: 3000
            }).show();
        }
      });
    }

    async function getSiweMessage(address) {
        const domain = window.location.host;
        const origin = window.location.origin;
        const statement = "Sign in with Ethereum to BlogChain.";
        const version = '1';
        const chain_id = '1';

        let res = await fetch(`${BACKEND_ADDR_AUTH}/nonce/${address}`);
        res = await res.json();
        const nonce = res.nonce;

        res = await fetch(`${BACKEND_ADDR_AUTH}/message/${address}`, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({ domain, origin, statement, version, chain_id, nonce }),
        });

        res = await res.json();

        return res.message;
    }

    async function signInWithEthereum() {
        const signer = accounts[0];

        message = await getSiweMessage(
            signer,
            "Sign in with Ethereum to BlogChain."
        );
        signature = await provider
            .request({
                method: "personal_sign",
                params: [message, signer]
            });
    }

    async function sendForVerification() {
        const signer = accounts[0];

        let res = await fetch(`${BACKEND_ADDR_AUTH}/verify/${signer}`, {
            method: "POST",
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ message, signature }),
        });
        res = await res.json();

        if (res.username) {
            window.location.href = `/app`;
        } else {
            window.location.href = `/auth/username`;
        }
    }

    async function login() {
        await connectWallet();
        await signInWithEthereum();
        await sendForVerification();
    }

    async function logout() {
        await provider
            .request({
                method: "wallet_revokePermissions",
                params: [
                    {
                        eth_accounts: {},
                    },
                ],
            });

        window.location.href = `/auth/logout`;
    }
</script>

{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        <script type="text/javascript">
            {% for category, message in messages %}
                new Noty({
                    type: '{{ category }}',
                    theme: 'bootstrap-v4',
                    layout: 'topCenter',
                    text: '{{ message }}',
                    timeout: 3000
                }).show();
            {% endfor %}
        </script>
    {% endif %}
{% endwith %}

templates/theme-toggle.html
<label class="theme-toggle">
    <input type="checkbox" id="theme-switch">
    <span class="slider round"></span>
</label>

templates/tips/send.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Tip | BlogChain</title>
    {% include "header.html" %}
</head>

<body class="light-theme">
    <div class="container mt-5">
        {% include "navbar.html" %}

        <div class="container mb-5">
            <div class="row mt-5">
                <div class="col-md-3 mx-auto">
                    <div class="alert alert-info text-center" role="alert">
                        <strong>Author:</strong> {{ post.author }}
                        <br>
                        <strong>Post ID:</strong> {{ post.id }}
                    </div>
                </div>
            </div>

            <div class="row justify-content-center">
                <div class="col-md-6 content-box low">
                    <h4 class="card-title text-center">Give Tip</h4>
                    <form onsubmit="tip(); return false;">
                        {{ tip_form.hidden_tag() }}
                        <div class="form-group">
                            {{ tip_form.sender.label(class="form-control-label") }}
                            {{ tip_form.sender(class="form-control", id="sender", placeholder="Enter your address")}}
                        </div>
                        <div class="form-group">
                            {{ tip_form.recipient.label(class="form-control-label") }}
                            {{ tip_form.recipient(class="form-control", id="recipient", placeholder="Enter recipient address") }}
                        </div>
                        <div class="form-group">
                            {{ tip_form.amount.label(class="form-control-label") }}
                            {{ tip_form.amount(class="form-control", id="amount", placeholder="Enter amount (in ETH)") }}
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Tip!</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% include "footer.html" %}

    {% include "scripts.html" %}

    <script>
        const BACKEND_ADDR_TIPS = "http://localhost:5000/tips";

        async function sendTransaction() {
            const sender = document.getElementById("sender").value;
            const recipient = document.getElementById("recipient").value;
            const amount = document.getElementById("amount").value;
            const post_id = "{{ post.id }}";

            await provider
                .request({
                    method: "eth_sendTransaction",
                    params: [
                         {
                            from: sender,
                            to: recipient,
                            value: Number(amount * 1e18).toString(16),
                         }
                    ]
                })
                .then((txHash) => {
                    fetch(`${BACKEND_ADDR_TIPS}/record`, {
                        method: "POST",
                        headers: {
                            "Content-Type": "application/json",
                        },
                        body: JSON.stringify({ sender, recipient, amount, post_id, txHash }),
                    });

                    new Noty({
                        type: "success",
                        theme: "bootstrap-v4",
                        layout: "topCenter",
                        text: "Tip sent.",
                        timeout: 3000
                    }).show();

                    const sleep = ms => new Promise(r => setTimeout(r, ms));
                    async function wait() {
                        await sleep(3500);
                    }

                    wait().then(() =>
                    {
                        window.location.href = `/app`;
                    });
                })
                .catch((err) => {
                    if (err.code === 4001) {
                        new Noty({
                            type: "error",
                            theme: "bootstrap-v4",
                            layout: "topCenter",
                            text: "Transaction rejected.",
                            timeout: 3000
                        }).show();
                    } else {
                        alert(err);
                    }
                });
        }

        async function tip() {
            await connectWallet();
            await sendTransaction();
        }
    </script>

</body>

</html>